// <auto-generated />
using System;
using DemoAcmeAp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoAcmeAp.Migrations
{
    [DbContext(typeof(DemoAcmeApContext))]
    partial class DemoAcmeApContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoAcmeAp.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EnderecoCobrancaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoCobrancaId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("DemoAcmeAp.Models.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("DemoAcmeAp.Models.Fatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InstalacaoId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumeroLeitura")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorConta")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InstalacaoId");

                    b.ToTable("Fatura");
                });

            modelBuilder.Entity("DemoAcmeAp.Models.Instalacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataInstalacao")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EnderecoInstalacaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EnderecoInstalacaoId");

                    b.ToTable("Instalacao");
                });

            modelBuilder.Entity("DemoAcmeAp.Models.Cliente", b =>
                {
                    b.HasOne("DemoAcmeAp.Models.Endereco", "EnderecoCobranca")
                        .WithMany()
                        .HasForeignKey("EnderecoCobrancaId");

                    b.Navigation("EnderecoCobranca");
                });

            modelBuilder.Entity("DemoAcmeAp.Models.Fatura", b =>
                {
                    b.HasOne("DemoAcmeAp.Models.Instalacao", "Instalacao")
                        .WithMany("ListFatura")
                        .HasForeignKey("InstalacaoId");

                    b.Navigation("Instalacao");
                });

            modelBuilder.Entity("DemoAcmeAp.Models.Instalacao", b =>
                {
                    b.HasOne("DemoAcmeAp.Models.Cliente", "Cliente")
                        .WithMany("ListaInstalacao")
                        .HasForeignKey("ClienteId");

                    b.HasOne("DemoAcmeAp.Models.Endereco", "EnderecoInstalacao")
                        .WithMany()
                        .HasForeignKey("EnderecoInstalacaoId");

                    b.Navigation("Cliente");

                    b.Navigation("EnderecoInstalacao");
                });

            modelBuilder.Entity("DemoAcmeAp.Models.Cliente", b =>
                {
                    b.Navigation("ListaInstalacao");
                });

            modelBuilder.Entity("DemoAcmeAp.Models.Instalacao", b =>
                {
                    b.Navigation("ListFatura");
                });
#pragma warning restore 612, 618
        }
    }
}
